/**
 * JavaScript implementation of `client/epub.gleam` plus the Lustre
 * file-input event helper.
 *
 * Two entry points:
 *
 *   - `parse_epub_file(file, on_complete)` — drive the vendored
 *     foliate-js parser. Reads the spine, projects each section's
 *     visible block elements into the segmenter's plain-text shape
 *     (`# Title`, blank-line paragraph breaks), and resolves the
 *     callback with `Ok(EpubExtract(...))` or `Error(epub_error)`.
 *
 *   - `file_change_attribute(decode_msg)` — produce a Lustre
 *     attribute that wires up `<input type="file">` onChange. Lustre
 *     v5's `event.on_change` only forwards `target.value` (the empty
 *     string for file inputs), so we hand-roll the event handler that
 *     pulls `target.files[0]` and dispatches it back through Gleam.
 *
 * Gleam runtime encoding is the same shape as `ffi.ffi.mjs`:
 * variants are constructed from the imported runtime classes
 * (`Ok`/`GleamError`, plus the `EpubExtract` / `Epub*Error`
 * constructors generated by the Gleam compiler), so the result values
 * round-trip cleanly back into pattern-matching on the reducer side.
 */

import { Ok, Error as GleamError } from "../gleam.mjs";
import {
  EpubExtract,
  UnsupportedFormat,
  DrmEncrypted,
  EmptyText,
  ParseFailed,
} from "./epub.mjs";
import { EPUB } from "./vendor/foliate-js/epub.js";
import {
  configure,
  ZipReader,
  BlobReader,
  TextWriter,
  BlobWriter,
} from "./vendor/foliate-js/vendor/zip.js";

// Foliate-js's reader UI spins up a web worker for zip decompression
// — we run the whole parse on the main thread so the bundler doesn't
// have to chase a worker entry. Disable workers once at module load
// time; `configure` is idempotent and cheap to repeat per call.
configure({ useWebWorkers: false });

// Block-level HTML elements whose text we extract as one paragraph
// each. `<p>` is the workhorse; `<blockquote>` / `<pre>` preserve
// indented prose; `<li>` flattens lists into one paragraph per item.
// Headings are handled separately below (the first `<h1>` / `<h2>`
// becomes a `# Title` line). Two consumers: the selector string built
// from `.join(",")` (drives `querySelectorAll` lookups) and the
// `.includes()` membership check inside the recursive walker (decides
// whether a child element is itself a block boundary). A plain array
// is the most honest shape for both uses — there are four entries, so
// `.includes()` is cheap.
const PARAGRAPH_TAGS = ["p", "blockquote", "pre", "li"];
const BLOCK_SELECTOR = PARAGRAPH_TAGS.join(",");

// Sniff the file's first four bytes for the ZIP local-file-header
// magic number (`PK\x03\x04`). A non-ZIP file (text, PDF, image) lands
// here on the rare path where the OS guessed the wrong MIME for the
// `accept=".epub"` filter — surface it as `UnsupportedFormat` rather
// than letting the zip reader throw a generic "invalid signature".
async function isZipFile(file) {
  if (!file || typeof file.slice !== "function") return false;
  const head = new Uint8Array(await file.slice(0, 4).arrayBuffer());
  return (
    head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04
  );
}

// Build the foliate-js loader interface from a ZipReader's entries.
// The same shape as foliate-js's own `makeZipLoader` in `view.js`,
// trimmed to the four callbacks `EPUB` actually consumes (`loadText`,
// `loadBlob`, `getSize`, plus a no-op `sha1` because we don't decrypt
// font obfuscation).
function makeLoader(entries) {
  const map = new Map(entries.map((entry) => [entry.filename, entry]));
  const callIfPresent = (fn) => (name, ...args) =>
    map.has(name) ? fn(map.get(name), ...args) : null;
  return {
    loadText: callIfPresent((entry) => entry.getData(new TextWriter())),
    loadBlob: callIfPresent((entry, type) =>
      entry.getData(new BlobWriter(type)),
    ),
    getSize: (name) => map.get(name)?.uncompressedSize ?? 0,
    // `sha1` is only invoked by foliate-js when the OPF marks
    // resources as obfuscated (Adobe / IDPF font mangling). We do not
    // need decrypted fonts to extract prose, so return a deterministic
    // 20-byte zero buffer rather than wiring up a SubtleCrypto round-
    // trip that could fail on insecure-context dev pages.
    //
    // Upstream-behavior dependency (pinned to vendored commit
    // 78914aef4466eb960965702401634c2cb348e9b1): foliate-js consumes
    // this hash only as an input to its font deobfuscation key
    // derivation — it never compares the value against the OPF's
    // declared hash. If a future bump of foliate-js starts checking
    // the returned bytes against a real digest, our prose-extraction
    // path silently miscomputes font keys (still fine, we don't read
    // fonts) but the assumption that "any 20-byte buffer is OK" will
    // need to be re-verified. The vendored snapshot is the source of
    // truth here — re-verify on every upstream bump.
    sha1: async () => new Uint8Array(20),
  };
}

// Foliate-js parses the OPF metadata into `{ title: [...], author:
// [...] }` (each field is an array because EPUB 3 metadata is
// repeatable). Reduce each to a single human-readable string. Authors
// may carry `{ name: "..." }` or be plain strings depending on the
// EPUB version — handle both.
function readTitle(metadata) {
  const titles = metadata?.title;
  if (!Array.isArray(titles) || titles.length === 0) return "";
  const first = titles[0];
  if (typeof first === "string") return first.trim();
  if (first && typeof first === "object" && typeof first.value === "string") {
    return first.value.trim();
  }
  return "";
}

function readAuthor(metadata) {
  const authors = metadata?.author;
  if (!Array.isArray(authors) || authors.length === 0) return "";
  const names = authors
    .map((author) => {
      if (typeof author === "string") return author.trim();
      if (author && typeof author === "object") {
        if (typeof author.name === "string") return author.name.trim();
        if (typeof author.value === "string") return author.value.trim();
      }
      return "";
    })
    .filter((name) => name.length > 0);
  // Multiple creators join with " & " so a co-authored book reads
  // naturally in the library card ("Strunk & White") rather than a
  // comma list that looks like a single name with a suffix.
  return names.join(" & ");
}

// Collapse all whitespace runs to a single space and trim — matches
// the WHATWG "strip and collapse ASCII whitespace" algorithm foliate-
// js uses internally on metadata. Applied to each block element's
// `.textContent` so soft line breaks inside the source XHTML do not
// fragment the rendered paragraph.
function normalizeWhitespace(text) {
  return text.replace(/[\t\n\f\r ]+/g, " ").trim();
}

// Walk a section's parsed XHTML document and append `# Heading`
// markers + paragraph bodies onto the running `chunks` array. Returns
// `true` when the section contributed at least one non-empty
// paragraph, so the caller can skip sections that yielded nothing
// (cover images, nav documents, blank stubs).
function extractSection(doc, chunks) {
  const body = doc?.body ?? doc?.documentElement;
  if (!body) return false;

  let emittedHeading = false;

  // Two passes through the same tree: the first finds the section's
  // title (first non-empty `<h1>` or `<h2>`), the second extracts the
  // body paragraphs. Two passes rather than one because the heading
  // must appear at the top of the chunk regardless of where it sits
  // structurally in the source XHTML (some publishers wrap the title
  // in a `<header>` element after the cover image).
  const headingNodes = body.querySelectorAll("h1, h2");
  for (const node of headingNodes) {
    const text = normalizeWhitespace(node.textContent ?? "");
    if (text.length === 0) continue;
    chunks.push(`# ${text}\n\n`);
    emittedHeading = true;
    break;
  }

  // Walk every top-level block (one with no matching block ancestor)
  // and emit its prose. `walkBlock` handles two shapes:
  //
  //   - A block with no nested matching block emits its entire text
  //     content as a single paragraph.
  //   - A block that does contain nested matching blocks walks its
  //     descendants in document order, flushing surrounding text runs
  //     into their own chunks at every nested-block boundary and
  //     recursing into each nested block.
  //
  // This preserves outer-block text adjacent to inner blocks — common
  // shapes that the previous "emit only the innermost block" rule
  // silently truncated:
  //
  //   `<blockquote><p>Quoted.</p>— Attribution.</blockquote>`
  //     → "Quoted." and "— Attribution." (pull-quote with citation)
  //   `<li>Header<ul><li>Sub A</li><li>Sub B</li></ul></li>`
  //     → "Header", "Sub A", "Sub B" (outline-style nested list)
  //
  // Skipping the recursion for top-level-only blocks keeps each
  // matching node visited at most once: nested blocks are reached via
  // their parent's walk, never the outer `querySelectorAll` loop.
  const before = chunks.length;
  for (const node of body.querySelectorAll(BLOCK_SELECTOR)) {
    if (hasMatchingAncestor(node)) continue;
    walkBlock(node, chunks);
  }
  const emittedParagraph = chunks.length > before;

  return emittedHeading || emittedParagraph;
}

// `true` when `node` has an ancestor that is itself a paragraph-block
// element. The outer `querySelectorAll` loop uses this to skip nested
// blocks — those are visited recursively from their parent walk
// instead, so we never emit the same prose twice.
function hasMatchingAncestor(node) {
  const parent = node.parentElement;
  if (parent === null) return false;
  return parent.closest(BLOCK_SELECTOR) !== null;
}

// Recursively walk a paragraph-block element, pushing one or more
// chunks onto `chunks`. The contract: every text node reachable from
// `node` that is not inside a nested matching block is emitted exactly
// once, in document order, with nested-block boundaries flushing the
// surrounding text run into its own chunk before recursing.
function walkBlock(node, chunks) {
  // Fast path — no nested matching blocks, so the whole subtree is one
  // paragraph. Avoids the recursive descent in the common case.
  if (node.querySelector(BLOCK_SELECTOR) === null) {
    pushChunk(node.textContent, chunks);
    return;
  }
  // Mixed-content path. `buffer` accumulates the text run between two
  // nested blocks (or before the first / after the last); `flush`
  // commits it as its own chunk and resets.
  const state = { buffer: "" };
  walkBlockChildren(node, state, chunks);
  flushBuffer(state, chunks);
}

function walkBlockChildren(node, state, chunks) {
  for (const child of node.childNodes) {
    if (child.nodeType === 1) {
      // ELEMENT_NODE
      const tag = child.tagName.toLowerCase();
      if (PARAGRAPH_TAGS.includes(tag)) {
        // Nested block boundary — commit the prior text run, then
        // recurse so the nested block emits its own chunk(s).
        flushBuffer(state, chunks);
        walkBlock(child, chunks);
      } else if (child.querySelector(BLOCK_SELECTOR) !== null) {
        // Inline wrapper (`<span>`, `<a>`, ...) that itself contains a
        // nested block. Descend so the block boundary still splits the
        // text run rather than swallowing the inner prose into the
        // current buffer via `.textContent`.
        walkBlockChildren(child, state, chunks);
      } else {
        // Inline element with no nested blocks — flatten its text into
        // the running buffer.
        state.buffer += child.textContent ?? "";
      }
    } else if (child.nodeType === 3) {
      // TEXT_NODE
      state.buffer += child.nodeValue ?? "";
    }
    // Comments, processing instructions, etc. are ignored.
  }
}

function flushBuffer(state, chunks) {
  pushChunk(state.buffer, chunks);
  state.buffer = "";
}

function pushChunk(rawText, chunks) {
  const text = normalizeWhitespace(rawText ?? "");
  if (text.length === 0) return;
  chunks.push(`${text}\n\n`);
}

// Drive a foliate-js EPUB instance to plain text. Returns the
// segmenter-shaped text (`# Heading\n\n`, paragraphs separated by
// `\n\n`, single newline reserved for in-paragraph breaks) plus a
// count of sections that failed to parse. The reducer surfaces a
// non-zero count as a soft warning in the add-book sheet so the
// reader can distinguish a complete import from a partial one.
async function renderSections(book) {
  const chunks = [];
  let sectionsSkipped = 0;
  for (const section of book.sections ?? []) {
    if (!section || section.linear === "no") continue;
    // `createDocument` returns a parsed XML/XHTML document for the
    // section. It can throw for malformed spine items — catch
    // section-level failures so one broken chapter does not abort the
    // whole import. Count the skip so the reducer can let the reader
    // know that the import was partial.
    let doc;
    try {
      doc = await section.createDocument();
    } catch (error) {
      console.warn("Failed to parse epub section", section.id, error);
      sectionsSkipped += 1;
      continue;
    }
    extractSection(doc, chunks);
  }
  return { text: chunks.join(""), sectionsSkipped };
}

/**
 * Parse an ePub `File` and resolve `on_complete` with either an
 * `EpubExtract` payload or one of the `EpubError` variants. Runs the
 * entire parse on the main thread (no web worker), which is fine for
 * the prose-extraction workload — a 500-page ePub finishes parsing in
 * a few hundred milliseconds on a modern laptop.
 *
 * @param {File} file Browser File object from the `<input type="file">`.
 * @param {function(Ok<EpubExtract>|GleamError): void} on_complete
 */
export function parse_epub_file(file, on_complete) {
  parseEpub(file)
    .then((extract) => {
      on_complete(new Ok(extract));
    })
    .catch((error) => {
      on_complete(new GleamError(toEpubError(error)));
    });
}

async function parseEpub(file) {
  if (!file) throw new UnsupportedFormatMarker("Missing file");
  if (!(await isZipFile(file))) {
    throw new UnsupportedFormatMarker("Not a ZIP container");
  }

  const reader = new ZipReader(new BlobReader(file));
  let entries;
  try {
    entries = await reader.getEntries();
  } catch (error) {
    throw new UnsupportedFormatMarker(
      error?.message ? `Zip read failed: ${error.message}` : "Zip read failed",
    );
  }

  const loader = makeLoader(entries);
  let book;
  try {
    book = await new EPUB(loader).init();
  } catch (error) {
    // foliate-js throws bare `Error("...")` for missing
    // container/OPF; the message text is the only signal we have for
    // the DRM-vs-malformed distinction.
    //
    // Upstream-string dependency (pinned to vendored commit
    // 78914aef4466eb960965702401634c2cb348e9b1): the `/encryption/i`
    // and `/drm/i` patterns are matched against the bare `error.message`
    // foliate-js produces today. A future bump that rephrases or
    // localises those error strings would silently regress the
    // `DrmEncrypted` branch into `UnsupportedFormat`. Re-verify on
    // every upstream bump that the error wording still contains one
    // of these tokens.
    const message = error?.message ?? "";
    if (/encryption/i.test(message) || /drm/i.test(message)) {
      throw new DrmEncryptedMarker(message);
    }
    throw new UnsupportedFormatMarker(message || "EPUB initialization failed");
  } finally {
    try {
      await reader.close();
    } catch (_close_error) {
      // Best-effort close — zip.js's BlobReader has no kernel
      // resource to release on the web side, so a close error here
      // does not affect the parsed result.
    }
  }

  const { text, sectionsSkipped } = await renderSections(book);
  if (text.trim().length === 0) {
    throw new EmptyTextMarker();
  }

  return new EpubExtract(
    readTitle(book.metadata),
    readAuthor(book.metadata),
    text,
    sectionsSkipped,
  );
}

// Marker classes carry the error shape from the inner parser to the
// outer `.catch` handler. Using plain Errors with discriminator
// strings would also work but the class hierarchy means a future
// `instanceof` check in tests is straightforward.
class UnsupportedFormatMarker extends Error {}
class DrmEncryptedMarker extends Error {}
class EmptyTextMarker extends Error {}

function toEpubError(error) {
  if (error instanceof UnsupportedFormatMarker) return new UnsupportedFormat();
  if (error instanceof DrmEncryptedMarker) return new DrmEncrypted();
  if (error instanceof EmptyTextMarker) return new EmptyText();
  const detail = error?.message ? String(error.message) : "Unknown parse error";
  return new ParseFailed(detail);
}

/**
 * Read the picked File out of a `change` event on a
 * `<input type="file">`. Lustre v5's `event.on_change` decoder only
 * forwards `event.target.value` (a string), which is empty for file
 * inputs and useless to us — this helper sits in the FFI so the view
 * can attach a typed handler that fires the parent message with the
 * raw `File` payload wrapped in a `Dynamic`.
 *
 * Pure read: extracts `event.target.files[0]` and returns it.
 * Resetting the input's `.value` (so picking the same file twice
 * still fires `change`) is done in a separate effect dispatched by
 * the `EpubFileSelected` reducer arm — keeping the decoder pure
 * matches Lustre's expectation that event decoders are
 * read-only event projections, not side-effect carriers.
 *
 * Returning `Error(Nil)` from the decoder when no file was picked
 * aborts the dispatch — same shape as Lustre's own decoders treating
 * "no value" as "no message".
 */
export function read_picked_file(event) {
  const file = event?.target?.files?.[0];
  if (!file) return new GleamError(undefined);
  return new Ok(file);
}

/**
 * Reset the value of every ePub-import file input in the DOM so a
 * subsequent pick of the same file still fires a `change` event.
 * Without this, the second selection of the same path silently
 * no-ops because the input's value did not change.
 *
 * Dispatched as an effect from the `EpubFileSelected` reducer arm
 * after the message has been read — the timing is async-safe because
 * the `File` reference has already been routed into the parse
 * effect by the time this runs.
 *
 * Some browsers throw when setting `.value` on a file input from
 * certain contexts; ignore — the worst case is the user has to pick
 * a different file to retry, which matches the pre-fix behaviour.
 */
export function reset_picker_inputs() {
  const inputs = document.querySelectorAll(".epub-import-input");
  for (const input of inputs) {
    try {
      input.value = "";
    } catch (_clear_error) {
      // Best-effort reset.
    }
  }
}
