/**
 * JavaScript implementation of `client/epub.gleam` plus the Lustre
 * file-input event helper.
 *
 * Two entry points:
 *
 *   - `parse_epub_file(file, on_complete)` — drive the vendored
 *     foliate-js parser. Reads the spine, projects each section's
 *     visible block elements into the segmenter's plain-text shape
 *     (`# Title`, blank-line paragraph breaks), and resolves the
 *     callback with `Ok(EpubExtract(...))` or `Error(epub_error)`.
 *
 *   - `file_change_attribute(decode_msg)` — produce a Lustre
 *     attribute that wires up `<input type="file">` onChange. Lustre
 *     v5's `event.on_change` only forwards `target.value` (the empty
 *     string for file inputs), so we hand-roll the event handler that
 *     pulls `target.files[0]` and dispatches it back through Gleam.
 *
 * Gleam runtime encoding is the same shape as `ffi.ffi.mjs`:
 * variants are constructed from the imported runtime classes
 * (`Ok`/`GleamError`, plus the `EpubExtract` / `Epub*Error`
 * constructors generated by the Gleam compiler), so the result values
 * round-trip cleanly back into pattern-matching on the reducer side.
 */

import { Ok, Error as GleamError } from "../gleam.mjs";
import {
  EpubExtract,
  UnsupportedFormat,
  DrmEncrypted,
  EmptyText,
  ParseFailed,
} from "./epub.mjs";
import { EPUB } from "./vendor/foliate-js/epub.js";
import {
  configure,
  ZipReader,
  BlobReader,
  TextWriter,
  BlobWriter,
} from "./vendor/foliate-js/vendor/zip.js";

// Foliate-js's reader UI spins up a web worker for zip decompression
// — we run the whole parse on the main thread so the bundler doesn't
// have to chase a worker entry. Disable workers once at module load
// time; `configure` is idempotent and cheap to repeat per call.
configure({ useWebWorkers: false });

// Block-level HTML elements whose `.textContent` we extract as one
// paragraph each. `<p>` is the workhorse; `<blockquote>` / `<pre>`
// preserve indented prose; `<li>` flattens lists into one paragraph
// per item. Headings are handled separately above (the first `<h1>` /
// `<h2>` becomes a `# Title` line).
const PARAGRAPH_TAGS = new Set(["p", "blockquote", "pre", "li"]);

// Heading tags we accept as the section title. We only emit a single
// `# Title` per section regardless of how many headings the section
// carries — the segmenter's chapter model is one-title-per-chapter,
// and most spine items only carry one h1/h2 anyway.
const HEADING_TAGS = new Set(["h1", "h2"]);

// Sniff the file's first four bytes for the ZIP local-file-header
// magic number (`PK\x03\x04`). A non-ZIP file (text, PDF, image) lands
// here on the rare path where the OS guessed the wrong MIME for the
// `accept=".epub"` filter — surface it as `UnsupportedFormat` rather
// than letting the zip reader throw a generic "invalid signature".
async function isZipFile(file) {
  if (!file || typeof file.slice !== "function") return false;
  const head = new Uint8Array(await file.slice(0, 4).arrayBuffer());
  return (
    head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04
  );
}

// Build the foliate-js loader interface from a ZipReader's entries.
// The same shape as foliate-js's own `makeZipLoader` in `view.js`,
// trimmed to the four callbacks `EPUB` actually consumes (`loadText`,
// `loadBlob`, `getSize`, plus a no-op `sha1` because we don't decrypt
// font obfuscation).
function makeLoader(entries) {
  const map = new Map(entries.map((entry) => [entry.filename, entry]));
  const callIfPresent = (fn) => (name, ...args) =>
    map.has(name) ? fn(map.get(name), ...args) : null;
  return {
    loadText: callIfPresent((entry) => entry.getData(new TextWriter())),
    loadBlob: callIfPresent((entry, type) =>
      entry.getData(new BlobWriter(type)),
    ),
    getSize: (name) => map.get(name)?.uncompressedSize ?? 0,
    // `sha1` is only invoked by foliate-js when the OPF marks
    // resources as obfuscated (Adobe / IDPF font mangling). We do not
    // need decrypted fonts to extract prose, so return a deterministic
    // empty buffer rather than wiring up a SubtleCrypto round-trip
    // that could fail on insecure-context dev pages.
    sha1: async () => new Uint8Array(20),
  };
}

// Foliate-js parses the OPF metadata into `{ title: [...], author:
// [...] }` (each field is an array because EPUB 3 metadata is
// repeatable). Reduce each to a single human-readable string. Authors
// may carry `{ name: "..." }` or be plain strings depending on the
// EPUB version — handle both.
function readTitle(metadata) {
  const titles = metadata?.title;
  if (!Array.isArray(titles) || titles.length === 0) return "";
  const first = titles[0];
  if (typeof first === "string") return first.trim();
  if (first && typeof first === "object" && typeof first.value === "string") {
    return first.value.trim();
  }
  return "";
}

function readAuthor(metadata) {
  const authors = metadata?.author;
  if (!Array.isArray(authors) || authors.length === 0) return "";
  const names = authors
    .map((author) => {
      if (typeof author === "string") return author.trim();
      if (author && typeof author === "object") {
        if (typeof author.name === "string") return author.name.trim();
        if (typeof author.value === "string") return author.value.trim();
      }
      return "";
    })
    .filter((name) => name.length > 0);
  // Multiple creators join with " & " so a co-authored book reads
  // naturally in the library card ("Strunk & White") rather than a
  // comma list that looks like a single name with a suffix.
  return names.join(" & ");
}

// Collapse all whitespace runs to a single space and trim — matches
// the WHATWG "strip and collapse ASCII whitespace" algorithm foliate-
// js uses internally on metadata. Applied to each block element's
// `.textContent` so soft line breaks inside the source XHTML do not
// fragment the rendered paragraph.
function normalizeWhitespace(text) {
  return text.replace(/[\t\n\f\r ]+/g, " ").trim();
}

// Walk a section's parsed XHTML document and append `# Heading`
// markers + paragraph bodies onto the running `chunks` array. Returns
// `true` when the section contributed at least one non-empty
// paragraph, so the caller can skip sections that yielded nothing
// (cover images, nav documents, blank stubs).
function extractSection(doc, chunks) {
  const body = doc?.body ?? doc?.documentElement;
  if (!body) return false;

  let emittedHeading = false;
  let emittedParagraph = false;

  // Two passes through the same tree: the first finds the section's
  // title (first non-empty `<h1>` or `<h2>`), the second extracts the
  // body paragraphs. Two passes rather than one because the heading
  // must appear at the top of the chunk regardless of where it sits
  // structurally in the source XHTML (some publishers wrap the title
  // in a `<header>` element after the cover image).
  const headingNodes = body.querySelectorAll("h1, h2");
  for (const node of headingNodes) {
    if (!HEADING_TAGS.has(node.tagName.toLowerCase())) continue;
    const text = normalizeWhitespace(node.textContent ?? "");
    if (text.length === 0) continue;
    chunks.push(`# ${text}\n\n`);
    emittedHeading = true;
    break;
  }

  // Walk block elements in document order. `querySelectorAll` returns
  // descendants in document order, and the segmenter treats nested
  // `<li>` inside `<blockquote>` etc. as one paragraph per innermost
  // block, which matches the visual reading the user sees in any
  // ePub reader.
  const blockSelector = Array.from(PARAGRAPH_TAGS).join(",");
  const blockNodes = body.querySelectorAll(blockSelector);
  for (const node of blockNodes) {
    const tag = node.tagName.toLowerCase();
    if (!PARAGRAPH_TAGS.has(tag)) continue;
    // Skip `<p>` and friends nested inside `<li>` to avoid emitting
    // the same prose twice — the outer `<li>` already captured the
    // textContent of its descendants.
    if (tag === "p" && node.closest("li")) continue;
    const text = normalizeWhitespace(node.textContent ?? "");
    if (text.length === 0) continue;
    chunks.push(`${text}\n\n`);
    emittedParagraph = true;
  }

  return emittedHeading || emittedParagraph;
}

// Drive a foliate-js EPUB instance to plain text. Returns a string
// in the segmenter's expected shape (`# Heading\n\n`, paragraphs
// separated by `\n\n`, single newline reserved for in-paragraph
// breaks the segmenter joins on whitespace anyway).
async function renderSections(book) {
  const chunks = [];
  for (const section of book.sections ?? []) {
    if (!section || section.linear === "no") continue;
    // `createDocument` returns a parsed XML/XHTML document for the
    // section. It can throw for malformed spine items — catch
    // section-level failures so one broken chapter does not abort the
    // whole import.
    let doc;
    try {
      doc = await section.createDocument();
    } catch (error) {
      console.warn("Failed to parse epub section", section.id, error);
      continue;
    }
    extractSection(doc, chunks);
  }
  return chunks.join("");
}

/**
 * Parse an ePub `File` and resolve `on_complete` with either an
 * `EpubExtract` payload or one of the `EpubError` variants. Runs the
 * entire parse on the main thread (no web worker), which is fine for
 * the prose-extraction workload — a 500-page ePub finishes parsing in
 * a few hundred milliseconds on a modern laptop.
 *
 * @param {File} file Browser File object from the `<input type="file">`.
 * @param {function(Ok<EpubExtract>|GleamError): void} on_complete
 */
export function parse_epub_file(file, on_complete) {
  parseEpub(file)
    .then((extract) => {
      on_complete(new Ok(extract));
    })
    .catch((error) => {
      on_complete(new GleamError(toEpubError(error)));
    });
}

async function parseEpub(file) {
  if (!file) throw new UnsupportedFormatMarker("Missing file");
  if (!(await isZipFile(file))) {
    throw new UnsupportedFormatMarker("Not a ZIP container");
  }

  const reader = new ZipReader(new BlobReader(file));
  let entries;
  try {
    entries = await reader.getEntries();
  } catch (error) {
    throw new UnsupportedFormatMarker(
      error?.message ? `Zip read failed: ${error.message}` : "Zip read failed",
    );
  }

  const loader = makeLoader(entries);
  let book;
  try {
    book = await new EPUB(loader).init();
  } catch (error) {
    // foliate-js throws bare `Error("...")` for missing
    // container/OPF; the message text is the only signal we have for
    // the DRM-vs-malformed distinction.
    const message = error?.message ?? "";
    if (/encryption/i.test(message) || /drm/i.test(message)) {
      throw new DrmEncryptedMarker(message);
    }
    throw new UnsupportedFormatMarker(message || "EPUB initialization failed");
  } finally {
    try {
      await reader.close();
    } catch (_close_error) {
      // Best-effort close — zip.js's BlobReader has no kernel
      // resource to release on the web side, so a close error here
      // does not affect the parsed result.
    }
  }

  const text = await renderSections(book);
  if (text.trim().length === 0) {
    throw new EmptyTextMarker();
  }

  return new EpubExtract(
    readTitle(book.metadata),
    readAuthor(book.metadata),
    text,
  );
}

// Marker classes carry the error shape from the inner parser to the
// outer `.catch` handler. Using plain Errors with discriminator
// strings would also work but the class hierarchy means a future
// `instanceof` check in tests is straightforward.
class UnsupportedFormatMarker extends Error {}
class DrmEncryptedMarker extends Error {}
class EmptyTextMarker extends Error {}

function toEpubError(error) {
  if (error instanceof UnsupportedFormatMarker) return new UnsupportedFormat();
  if (error instanceof DrmEncryptedMarker) return new DrmEncrypted();
  if (error instanceof EmptyTextMarker) return new EmptyText();
  const detail = error?.message ? String(error.message) : "Unknown parse error";
  return new ParseFailed(detail);
}

/**
 * Read the picked File out of a `change` event on a
 * `<input type="file">`. Lustre v5's `event.on_change` decoder only
 * forwards `event.target.value` (a string), which is empty for file
 * inputs and useless to us — this helper sits in the FFI so the view
 * can attach a typed handler that fires the parent message with the
 * raw `File` payload wrapped in a `Dynamic`.
 *
 * The arrangement mirrors the pattern used by `on_resize` in
 * `ffi.ffi.mjs`: the FFI installs the listener, normalises the
 * event, and dispatches a Gleam-runtime callback back to the caller.
 * The exported function returns a Lustre-compatible Attribute by
 * delegating to `event.on("change", decoder)` with a custom decoder
 * that pulls `event.target.files?.[0]` and returns it as a `Dynamic`.
 *
 * Returning `null` from the decoder when no file was picked aborts
 * the dispatch — same shape as Lustre's own decoders treating "no
 * value" as "no message".
 */
export function read_picked_file(event) {
  const target = event?.target;
  const file = target?.files?.[0];
  if (!file) return new GleamError(undefined);
  // Reset the input's value so picking the same file twice still
  // fires a `change` event. Without this, the second selection of
  // the same path silently no-ops because the input's value did not
  // change. The reset is async-safe — the File object we just read
  // is fully detached from the input by the time the assignment
  // runs.
  try {
    target.value = "";
  } catch (_clear_error) {
    // Some browsers throw when setting `.value` on a file input from
    // certain contexts; ignore — the worst case is the user has to
    // pick a different file to retry, which is the pre-fix behaviour.
  }
  return new Ok(file);
}
